#!/usr/bin/env bash

# Function to get and display subdomain information
get_subdomain_info() {
  local subdomain=$1
  local domain=$2
  local record=$(dig "$subdomain.$domain" +short)
  if [ -n "$record" ]; then
    echo "The subdomain $subdomain is a A record and points to $record"
  else
    echo "The subdomain $subdomain does not exist"
  fi
}

# Check if at least one argument is provided
if [ $# -lt 1 ]; then
  echo "Usage: $0 domain [subdomain]"
  exit 1
fi

# Set domain name
domain="$1"

# Check if a specific subdomain is provided
if [ $# -eq 2 ]; then
  get_subdomain_info "$2" "$domain"
else
  # Default subdomains to query
  subdomains=("www" "lb-01" "web-01" "web-02")

  # Loop through default subdomains and display information
  for subdomain in "${subdomains[@]}"; do
    get_subdomain_info "$subdomain" "$domain"
  done
fi

